### ISSUE TITLE
FHIR API integration

### ISSUE THREAD

**Issue by misaka** [nhsuk/record-childrens-vaccinations#36]
When a vaccination record has been created a process should update a central vaccination record via a FHIR API call. The FHIR endpoint should be configurable as that will certainly change, and we should include instructions for providing how to handle this in development mode, either a feature flag to disable FHIR integration, a dummy server setup locally, or instruction on how to setup a dev FHIR server somewhere.

**Comment by tvararu** [comment]
I think we can better scope/handle this in a Trello Epic when it becomes a priority, and don't need to keep this issue around. Closing for now.
