### ISSUE TITLE
Storage of child vaccination records in global `window` object.

### ISSUE THREAD

**Issue by misaka** [nhsuk/record-childrens-vaccinations#38]
As implemented in #34, child vaccination records are stored in the global `window` object. This was done with expediancy in mind over and may not be the best practice and may present security or other risks.

This decision should be re-examined and whatever the best practice is for this should be implemented.

**Comment by tvararu** [comment]
Closed by https://github.com/nhsuk/record-childrens-vaccinations/issues/38.
